package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// Generator обрабатывает парсинг AST и генерацию кода для методов Reset.
type Generator struct {
	fset           *token.FileSet
	packages       map[string]*ast.Package
	generatedFiles map[string]string
}

// NewGenerator создаёт новый экземпляр Generator.
func NewGenerator() *Generator {
	return &Generator{
		fset:           token.NewFileSet(),
		packages:       make(map[string]*ast.Package),
		generatedFiles: make(map[string]string),
	}
}

// ScanPackages сканирует Go-пакеты по указанным путям.
func (g *Generator) ScanPackages(paths []string) error {
	for _, path := range paths {
		if err := filepath.Walk(path, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				base := filepath.Base(path)
				if strings.HasPrefix(base, ".") || strings.HasSuffix(base, "_test") {
					return filepath.SkipDir
				}
			}
			return nil
		}); err != nil {
			return fmt.Errorf("failed to walk path %s: %w", path, err)
		}

		pkgs, err := parser.ParseDir(g.fset, path, func(info os.FileInfo) bool {
			name := info.Name()
			return !strings.HasSuffix(name, "_test.go") &&
				!strings.HasSuffix(name, "reset.gen.go") &&
				strings.HasSuffix(name, ".go")
		}, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("failed to parse package in %s: %w", path, err)
		}

		for name, pkg := range pkgs {
			g.packages[path+":"+name] = pkg
		}
	}
	return nil
}

// FindMarkedStructs находит все структуры с комментарием // generate:reset.
func (g *Generator) FindMarkedStructs() []StructInfo {
	var structs []StructInfo

	for pkgPath, pkg := range g.packages {
		parts := strings.SplitN(pkgPath, ":", 2)
		dir := parts[0]
		pkgName := parts[1]

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if !hasGenerateResetComment(genDecl.Doc) {
						continue
					}

					fields := extractFields(structType)
					structs = append(structs, StructInfo{
						Name:      typeSpec.Name.Name,
						Package:   pkgName,
						Directory: dir,
						Fields:    fields,
					})
				}
			}
		}
	}

	return structs
}

// hasGenerateResetComment проверяет наличие // generate:reset в комментариях.
func hasGenerateResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "generate:reset") {
			return true
		}
	}
	return false
}

// extractFields извлекает информацию о полях структуры.
func extractFields(structType *ast.StructType) []FieldInfo {
	var fields []FieldInfo

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		for _, name := range field.Names {
			if !name.IsExported() {
				continue
			}
			fields = append(fields, FieldInfo{
				Name: name.Name,
				Type: field.Type,
			})
		}
	}

	return fields
}

// generateResetMethodBody генерирует только тело метода Reset() для структуры.
func (g *Generator) generateResetMethodBody(structInfo StructInfo) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("func (rs *%s) Reset() {\n", structInfo.Name))

	for _, field := range structInfo.Fields {
		code, err := g.generateFieldReset(field, structInfo.Package)
		if err != nil {
			return nil, fmt.Errorf("failed to generate reset for field %s: %w", field.Name, err)
		}
		buf.WriteString(code)
	}

	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

// GenerateResetMethod генерирует код метода Reset() для структуры.
func (g *Generator) GenerateResetMethod(structInfo StructInfo) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	buf.WriteString("package ")
	buf.WriteString(structInfo.Package)
	buf.WriteString("\n\n")

	imports := make(map[string]string)
	g.collectImports(structInfo, imports)

	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for path, alias := range imports {
			if alias != "" {
				buf.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, path))
			} else {
				buf.WriteString(fmt.Sprintf("\t\"%s\"\n", path))
			}
		}
		buf.WriteString(")\n\n")
	}

	buf.WriteString(fmt.Sprintf("func (rs *%s) Reset() {\n", structInfo.Name))

	for _, field := range structInfo.Fields {
		code, err := g.generateFieldReset(field, structInfo.Package)
		if err != nil {
			return nil, fmt.Errorf("failed to generate reset for field %s: %w", field.Name, err)
		}
		buf.WriteString(code)
	}

	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

// collectImports собирает необходимые импорты из полей структуры.
func (g *Generator) collectImports(structInfo StructInfo, imports map[string]string) {
	seen := make(map[string]bool)

	for _, field := range structInfo.Fields {
		g.findImports(field.Type, imports, seen)
	}
}

// findImports рекурсивно находит импорты, необходимые для типа.
func (g *Generator) findImports(expr ast.Expr, imports map[string]string, seen map[string]bool) {
	switch t := expr.(type) {
	case *ast.Ident:

	case *ast.StarExpr:
		g.findImports(t.X, imports, seen)

	case *ast.SelectorExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			path := ident.Name
			if !seen[path] {
				seen[path] = true
				imports[path] = ""
			}
		}

	case *ast.ArrayType:
		g.findImports(t.Elt, imports, seen)

	case *ast.MapType:
		g.findImports(t.Key, imports, seen)
		g.findImports(t.Value, imports, seen)
	}
}

// generateFieldReset генерирует код сброса для одного поля.
func (g *Generator) generateFieldReset(field FieldInfo, currentPackage string) (string, error) {
	switch field.Type.(type) {
	case *ast.Ident:
		typeName := field.Type.(*ast.Ident).Name
		code, err := generateIdentReset(typeName)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("\trs.%s%s\n", field.Name, code), nil

	case *ast.StarExpr:
		inner := field.Type.(*ast.StarExpr).X
		code, err := generatePointerFieldReset(field.Name, inner)
		if err != nil {
			return "", err
		}
		return code, nil

	case *ast.SelectorExpr:
		return fmt.Sprintf("\trs.%s.Reset()\n", field.Name), nil

	case *ast.ArrayType, *ast.SliceExpr:
		return fmt.Sprintf("\trs.%s = rs.%s[:0]\n", field.Name, field.Name), nil

	case *ast.MapType:
		return fmt.Sprintf("\tclear(rs.%s)\n", field.Name), nil

	default:
		return "", fmt.Errorf("unsupported type for field %s: %T", field.Name, field.Type)
	}
}

// generatePointerFieldReset генерирует код сброса для указателей.
func generatePointerFieldReset(fieldName string, inner ast.Expr) (string, error) {
	switch t := inner.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64",
			"string", "bool", "byte", "rune", "uintptr":
			return fmt.Sprintf("\tif rs.%s != nil { *rs.%s = 0 }\n", fieldName, fieldName), nil
		default:
			return fmt.Sprintf("\tif rs.%s != nil { rs.%s.Reset() }\n", fieldName, fieldName), nil
		}

	case *ast.StarExpr:
		return fmt.Sprintf("\tif rs.%s != nil { rs.%s.Reset() }\n", fieldName, fieldName), nil

	case *ast.SelectorExpr:
		return fmt.Sprintf("\tif rs.%s != nil { rs.%s.Reset() }\n", fieldName, fieldName), nil

	default:
		return fmt.Sprintf("\tif rs.%s != nil { rs.%s.Reset() }\n", fieldName, fieldName), nil
	}
}

// generateIdentReset генерирует код сброса для идентификаторов.
func generateIdentReset(name string) (string, error) {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128":
		return " = 0", nil
	case "byte", "rune", "uintptr":
		return " = 0", nil
	case "string":
		return ` = ""`, nil
	case "bool":
		return " = false", nil
	default:
		return ".Reset()", nil
	}
}

// GenerateCode генерирует все методы Reset и записывает их в файлы.
func (g *Generator) GenerateCode(structs []StructInfo) error {
	dirStructs := make(map[string][]StructInfo)
	for _, s := range structs {
		dirStructs[s.Directory] = append(dirStructs[s.Directory], s)
	}

	for dir, structsInDir := range dirStructs {
		var buf bytes.Buffer
		if len(structsInDir) == 0 {
			continue
		}

		buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
		buf.WriteString("package ")
		buf.WriteString(structsInDir[0].Package)
		buf.WriteString("\n\n")

		for _, structInfo := range structsInDir {
			method, err := g.generateResetMethodBody(structInfo)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error generating code for %s: %v\n", structInfo.Name, err)
				continue
			}
			buf.Write(method)
			buf.WriteString("\n")
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			formatted = buf.Bytes()
		}

		outputPath := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
			continue
		}

		for _, s := range structsInDir {
			g.generatedFiles[outputPath] = s.Name
		}
	}
	return nil
}

// GetGeneratedFiles возвращает карту сгенерированных файлов.
func (g *Generator) GetGeneratedFiles() map[string]string {
	return g.generatedFiles
}

// StructInfo содержит информацию о структуре для генерации Reset().
type StructInfo struct {
	Name      string
	Package   string
	Directory string
	Fields    []FieldInfo
}

// FieldInfo содержит информацию о поле структуры.
type FieldInfo struct {
	Name string
	Type ast.Expr
}