package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator обрабатывает парсинг AST и генерацию кода для методов Reset.
type Generator struct {
	fset           *token.FileSet
	packages       map[string]*ast.Package
	generatedFiles map[string]string
}

// NewGenerator создаёт новый экземпляр Generator.
func NewGenerator() *Generator {
	return &Generator{
		fset:           token.NewFileSet(),
		packages:       make(map[string]*ast.Package),
		generatedFiles: make(map[string]string),
	}
}

// ScanPackages сканирует Go-пакеты по указанным путям рекурсивно.
func (g *Generator) ScanPackages(paths []string) error {
	for _, root := range paths {
		var dirs []string

		if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				base := filepath.Base(path)
				if strings.HasPrefix(base, ".") || strings.HasSuffix(base, "_test") {
					return filepath.SkipDir
				}
				dirs = append(dirs, path)
			}
			return nil
		}); err != nil {
			return fmt.Errorf("failed to walk path %s: %w", root, err)
		}

		for _, dir := range dirs {
			pkgs, err := parser.ParseDir(g.fset, dir, func(info os.FileInfo) bool {
				name := info.Name()
				return !strings.HasSuffix(name, "_test.go") &&
					!strings.HasSuffix(name, "reset.gen.go") &&
					strings.HasSuffix(name, ".go")
			}, parser.ParseComments)
			if err != nil {
				return fmt.Errorf("failed to parse package in %s: %w", dir, err)
			}

			for name, pkg := range pkgs {
				g.packages[dir+":"+name] = pkg
			}
		}
	}
	return nil
}

// FindMarkedStructs находит все структуры с комментарием // generate:reset.
func (g *Generator) FindMarkedStructs() []StructInfo {
	var structs []StructInfo

	for pkgPath, pkg := range g.packages {
		parts := strings.SplitN(pkgPath, ":", 2)
		dir := parts[0]
		pkgName := parts[1]

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if !hasGenerateResetComment(genDecl.Doc) {
						continue
					}

					fields := extractFields(structType)
					structs = append(structs, StructInfo{
						Name:      typeSpec.Name.Name,
						Package:   pkgName,
						Directory: dir,
						Fields:    fields,
					})
				}
			}
		}
	}

	return structs
}

// hasGenerateResetComment проверяет наличие // generate:reset в комментариях.
func hasGenerateResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "generate:reset") {
			return true
		}
	}
	return false
}

// extractFields извлекает информацию о полях структуры.
func extractFields(structType *ast.StructType) []FieldInfo {
	var fields []FieldInfo

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		for _, name := range field.Names {
			fields = append(fields, FieldInfo{
				Name: name.Name,
				Type: field.Type,
			})
		}
	}

	return fields
}

// --- Типы данных для шаблонов ---

type fileTmplData struct {
	PackageName string
	Imports     []importTmpl
	Structs     []structTmplData
}

type structTmplData struct {
	Name   string
	Fields []fieldTmplData
}

type fieldTmplData struct {
	ResetCode string
}

type importTmpl struct {
	Path  string
	Alias string
}

// --- Шаблоны ---

const resetMethodTmplText = `func (rs *{{.Name}}) Reset() {
{{- range .Fields }}	{{ .ResetCode }}
{{- end }}
}
`

const fileTmplText = `// Code generated by cmd/reset. DO NOT EDIT.

package {{.PackageName}}
{{- if .Imports }}

import (
{{- range .Imports }}	{{- if .Alias }}{{ .Alias }} {{ end }}"{{ .Path }}"
{{- end }})
{{- end }}
{{- range .Structs }}

{{template "method" .}}
{{- end }}
`

var fileTmpl = template.Must(template.New("file").Parse(fileTmplText))

var _ = template.Must(fileTmpl.New("method").Parse(resetMethodTmplText))

// buildStructTmplData собирает structTmplData из StructInfo.
func buildStructTmplData(s StructInfo, pkg string) structTmplData {
	fields := make([]fieldTmplData, 0, len(s.Fields))
	for _, f := range s.Fields {
		code, err := generateFieldReset(f, pkg)
		if err != nil {
			continue
		}
		fields = append(fields, fieldTmplData{ResetCode: code})
	}
	return structTmplData{Name: s.Name, Fields: fields}
}

// --- Генерация ---

// GenerateResetMethod генерирует полный .go-файл с методом Reset() для одной структуры.
func (g *Generator) GenerateResetMethod(structInfo StructInfo) ([]byte, error) {
	importsMap := make(map[string]string)
	g.collectImports(structInfo, importsMap)
	imports := mapToSlice(importsMap)
	data := fileTmplData{
		PackageName: structInfo.Package,
		Imports:     imports,
		Structs:     []structTmplData{buildStructTmplData(structInfo, structInfo.Package)},
	}

	return executeTemplate(fileTmpl, data)
}

// GenerateCode генерирует все методы Reset и записывает их в файлы.
func (g *Generator) GenerateCode(structs []StructInfo) error {
	dirStructs := make(map[string][]StructInfo)
	for _, s := range structs {
		dirStructs[s.Directory] = append(dirStructs[s.Directory], s)
	}

	for dir, structsInDir := range dirStructs {
		if len(structsInDir) == 0 {
			continue
		}

		pkg := structsInDir[0].Package
		imports := g.collectDirImports(structsInDir)

		structsData := make([]structTmplData, 0, len(structsInDir))
		for _, s := range structsInDir {
			structsData = append(structsData, buildStructTmplData(s, pkg))
		}

		data := fileTmplData{
			PackageName: pkg,
			Imports:     imports,
			Structs:     structsData,
		}

		out, err := executeTemplate(fileTmpl, data)
		if err != nil {
			return fmt.Errorf("failed to execute template: %w", err)
		}

		formatted, err := format.Source(out)
		if err != nil {
			formatted = out
		}

		outputPath := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
			continue
		}

		for _, s := range structsInDir {
			g.generatedFiles[outputPath] = s.Name
		}
	}
	return nil
}

// executeTemplate выполняет шаблон и возвращает результат.
func executeTemplate(t *template.Template, data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// --- Импорты ---

// collectImports собирает необходимые импорты из полей структуры.
func (g *Generator) collectImports(structInfo StructInfo, imports map[string]string) {
	seen := make(map[string]bool)

	for _, field := range structInfo.Fields {
		g.findImports(field.Type, imports, seen)
	}
}

// collectDirImports собирает импорты для всех структур в директории.
func (g *Generator) collectDirImports(structs []StructInfo) []importTmpl {
	imports := make(map[string]string)
	for _, s := range structs {
		g.collectImports(s, imports)
	}
	return mapToSlice(imports)
}

// mapToSlice конвертирует map[string]string (path → alias) в срез importTmpl.
func mapToSlice(m map[string]string) []importTmpl {
	if len(m) == 0 {
		return nil
	}
	result := make([]importTmpl, 0, len(m))
	for path, alias := range m {
		result = append(result, importTmpl{Path: path, Alias: alias})
	}
	return result
}

// findImports рекурсивно находит импорты, необходимые для типа.
func (g *Generator) findImports(expr ast.Expr, imports map[string]string, seen map[string]bool) {
	switch t := expr.(type) {
	case *ast.Ident:

	case *ast.StarExpr:
		g.findImports(t.X, imports, seen)

	case *ast.SelectorExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			path := ident.Name
			if !seen[path] {
				seen[path] = true
				imports[path] = ""
			}
		}

	case *ast.ArrayType:
		g.findImports(t.Elt, imports, seen)

	case *ast.MapType:
		g.findImports(t.Key, imports, seen)
		g.findImports(t.Value, imports, seen)
	}
}

// --- Генерация кода сброса для поля ---

// generateFieldReset генерирует код сброса для одного поля.
func generateFieldReset(field FieldInfo, currentPackage string) (string, error) {
	switch field.Type.(type) {
	case *ast.Ident:
		typeName := field.Type.(*ast.Ident).Name
		code, err := generateIdentReset(typeName)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("rs.%s%s", field.Name, code), nil

	case *ast.StarExpr:
		inner := field.Type.(*ast.StarExpr).X
		code, err := generatePointerFieldReset(field.Name, inner)
		if err != nil {
			return "", err
		}
		return code, nil

	case *ast.SelectorExpr:
		return fmt.Sprintf("rs.%s.Reset()", field.Name), nil

	case *ast.ArrayType, *ast.SliceExpr:
		return fmt.Sprintf("rs.%s = rs.%s[:0]", field.Name, field.Name), nil

	case *ast.MapType:
		return fmt.Sprintf("clear(rs.%s)", field.Name), nil

	default:
		return "", fmt.Errorf("unsupported type for field %s: %T", field.Name, field.Type)
	}
}

// generatePointerFieldReset генерирует код сброса для указателей.
func generatePointerFieldReset(fieldName string, inner ast.Expr) (string, error) {
	switch t := inner.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "byte", "rune", "uintptr":
			return fmt.Sprintf("if rs.%s != nil { *rs.%s = 0 }", fieldName, fieldName), nil
		case "string":
			return fmt.Sprintf("if rs.%s != nil { *rs.%s = \"\" }", fieldName, fieldName), nil
		case "bool":
			return fmt.Sprintf("if rs.%s != nil { *rs.%s = false }", fieldName, fieldName), nil
		default:
			return fmt.Sprintf("if rs.%s != nil { rs.%s.Reset() }", fieldName, fieldName), nil
		}

	case *ast.StarExpr:
		return fmt.Sprintf("if rs.%s != nil { rs.%s.Reset() }", fieldName, fieldName), nil

	case *ast.SelectorExpr:
		return fmt.Sprintf("if rs.%s != nil { rs.%s.Reset() }", fieldName, fieldName), nil

	default:
		return fmt.Sprintf("if rs.%s != nil { rs.%s.Reset() }", fieldName, fieldName), nil
	}
}

// generateIdentReset генерирует код сброса для идентификаторов.
func generateIdentReset(name string) (string, error) {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128":
		return " = 0", nil
	case "byte", "rune", "uintptr":
		return " = 0", nil
	case "string":
		return ` = ""`, nil
	case "bool":
		return " = false", nil
	default:
		return ".Reset()", nil
	}
}

// GetGeneratedFiles возвращает карту сгенерированных файлов.
func (g *Generator) GetGeneratedFiles() map[string]string {
	return g.generatedFiles
}

// StructInfo содержит информацию о структуре для генерации Reset().
type StructInfo struct {
	Name      string
	Package   string
	Directory string
	Fields    []FieldInfo
}

// FieldInfo содержит информацию о поле структуры.
type FieldInfo struct {
	Name string
	Type ast.Expr
}
